version: 0.1
phases:
  install:
    commands:
      - npm install time
      - cd src; npm install; cd ..
  build:
    commands:
      - aws cloudformation package
         --template-file template.yaml
         --s3-bucket $S3_BUCKET_NAME
         --output-template-file samTemplate.yaml
      - aws s3 cp `./src/node_modules/yaml-cli/libexec/yaml get samTemplate.yaml Resources.LambdaFunction.Properties.CodeUri` s3://876224653878-sungardas-aws-services-alerts-s3-eu-west-1  --acl public-read
      - sed -i "s/$S3_BUCKET_NAME/876224653878-sungardas-aws-services-alerts-s3-eu-west-1/g" samTemplate.yaml
      - aws s3 cp ./samTemplate.yaml s3://876224653878-sungardas-aws-services-alerts-s3-eu-west-1 --acl public-read
artifacts:
  type: zip
  files:
    - samTemplate.yaml
