version: 0.1
phases:
  install:
    commands:
      - npm install time
      - cd src; npm install; cd ..
      - aws cloudformation package
         --template-file template.yaml
         --s3-bucket $S3_BUCKET_NAME
         --output-template-file samTemplate.yaml
  post_build:
    commands:
      - aws s3 cp ./samTemplate.yaml s3://876224653878-sungardas-aws-services-alerts-s3-eu-west-1 --acl public-read
artifacts:
  type: zip
  files:
    - samTemplate.yaml
