version: 0.1
phases:
  install:
    commands:
      - npm install time
      - cd src; npm install; cd ..
  build:
    commands:
      - aws cloudformation package
         --template-file template.yaml
         --s3-bucket $S3_BUCKET_NAME
         --output-template-file samTemplate.yaml
  post_build:
    commands:
      - s3 cp `./src/node_modules/yaml-cli/libexec/yaml get samTemplate.yaml Resources.LambdaFunction.Properties.CodeUri` s3://$S3_SHARED_BUCKET_NAME  --acl public-read
      - sed -i "s/$S3_BUCKET_NAME/$S3_SHARED_BUCKET_NAME/g" samTemplate.yaml
      - aws s3 cp ./samTemplate.yaml s3://$S3_SHARED_BUCKET_NAME/`python -c 'import sys,uuid; sys.stdout.write(uuid.uuid4().hex)' | pbcopy && pbpaste && echo`.yaml --acl public-read
artifacts:
  type: zip
  files:
    - samTemplate.yaml
