AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation to Set up a aws-services-alerts Project CodePipeline along with CodeBuild

Parameters:
  GitHubSourceRepositoryOwner:
    Type: String
    Default: SungardAS
    Description: Owner of the Source Repository in GitHub
  GitHubSourceRepositoryName:
    Type: String
    Description: Name of the Source Repository in GitHub
  GitHubSourceRepositoryBranch:
    Type: String
    Default: master
    Description: Branch of the Source Repository in GitHub
  GitHubPersonalAccessToken:
    Type: String
    NoEcho: true
    Description: Personal Access Token to Access GitHub Repository
  ProjectImage:
    Type: String
    AllowedValues:
      - "aws/codebuild/amazonlinux2-aarch64-standard:1.0"
      - "aws/codebuild/amazonlinux2-x86_64-standard:2.0"
      - "aws/codebuild/standard:2.0"
      - "aws/codebuild/standard:3.0"
    Description: Implemented Programming Language
  CustomAuthorizerLambdaName:
    Type: String
    Description: Name of the Custom Authorizer Lambda Function
  CustomAuthorizerIAMRoleName:
    Type: String
    Description: Name of IAM Role to Execute Custom Authorizer Lambda Function
  EncryptionLambdaName:
    Type: String
    Default: ""
    Description: Encryption Lambda Function Name when This Project Lambda Function has Secret Environment Variables to be Encrypted
  CloudWatchLogDestinationName:
    Type: String
    Default: "alertDestination"
    Description: Alert Kinesis Destination Name
  AlertMessageDynamoDBTableName:
    Type: String
    Default: ""
    Description: DynamoDB Table Name to Store Alert Messages
  SlackWebHookUrl:
    Type: String
    NoEcho: true
    Description: Slack Webhook Url without 'https://'
  SlackChannel:
    Type: String
    Default: "#alert"
    Description: Slack Channel Name
  TeamsWebHookUrl:
    Type: String
    NoEcho: true
    Description: Teams Webhook Url without 'https://'
  AlertTopicSubEndpointForCTO:
    Type: String
    Description: Email Address for Alet Message Notification
Conditions:
  HasCustomAuthorizerLambdaName: !Not [!Equals [!Ref CustomAuthorizerLambdaName, ""]]
  HasCustomAuthorizerIAMRoleName: !Not [!Equals [!Ref CustomAuthorizerIAMRoleName, ""]]
  HasEncryptionLambda: !Not [!Equals [!Ref EncryptionLambdaName, ""]]

Resources:
  CodeBuildServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
          Path: "/"
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Sid: "AllowCodebuildToAssumeRole"
                Effect: "Allow"
                Action:
                  - "sts:AssumeRole"
                Principal:
                  Service:
                    - "codebuild.amazonaws.com"
          Policies:
            -
              PolicyName: "InlinePolicy"
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  -
                    Effect: "Allow"
                    Action:
                      - "logs:CreateLogGroup"
                      - "logs:CreateLogStream"
                      - "logs:PutLogEvents"
                    Resource:
                      - !Join
                        - ''
                        - - "arn:aws:logs:"
                          - !Ref AWS::Region
                          - ":"
                          - !Ref AWS::AccountId
                          - ":log-group:/aws/codebuild/*"
                  -
                    Effect: "Allow"
                    Action:
                      - "s3:GetObject"
                      - "s3:GetObjectVersion"
                      - "s3:PutObject"
                    Resource:
                      - !Join
                        - ''
                        - - "arn:aws:s3:::"
                          - !Ref InputArtifactS3Bucket
                          - "/*"
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Join
          - '-'
          - - !Ref GitHubSourceRepositoryOwner
            - !Ref GitHubSourceRepositoryName
            - "codebuild"
      Description: CodeBuild for a Project aws-services-alerts
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref ProjectImage
        EnvironmentVariables:
        - Name: S3_BUCKET_NAME
          Value: !Ref InputArtifactS3Bucket
        - Name: AWS_DEFAULT_REGION
          Value: !Ref AWS::Region
        - Name: AWS_ACCOUNT_ID
          Value: !Ref AWS::AccountId
        -
          !If
            - HasCustomAuthorizerLambdaName
            -
              Name: CUSTOM_AUTHORIZER_LAMBDA_NAME
              Value: !Ref CustomAuthorizerLambdaName
            - !Ref "AWS::NoValue"
        -
          !If
            - HasCustomAuthorizerIAMRoleName
            -
              Name: CUSTOM_AUTHORIZER_ROLE_NAME
              Value: !Ref CustomAuthorizerIAMRoleName
            - !Ref "AWS::NoValue"
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 60
  InputArtifactS3Bucket:
    Type: "AWS::S3::Bucket"
  CodePipelineServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
          Path: "/"
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Sid: "AllowCodePipelineToAssumeRole"
                Effect: "Allow"
                Action:
                  - "sts:AssumeRole"
                Principal:
                  Service:
                    - "codepipeline.amazonaws.com"
          Policies:
            -
              PolicyName: "InlinePolicy"
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  -
                    Effect: "Allow"
                    Action:
                      - "s3:PutObject"
                    Resource:
                      - "arn:aws:s3:::codepipeline*"
                      - "arn:aws:s3:::elasticbeanstalk*"
                  -
                    Effect: "Allow"
                    Action:
                      - "s3:GetObject"
                      - "s3:GetObjectVersion"
                      - "s3:PutObject"
                    Resource: "*"
                  -
                    Effect: "Allow"
                    Action:
                      - "codecommit:CancelUploadArchive"
                      - "codecommit:GetBranch"
                      - "codecommit:GetCommit"
                      - "codecommit:GetUploadArchiveStatus"
                      - "codecommit:UploadArchive"
                    Resource: "*"
                  -
                    Effect: "Allow"
                    Action:
                      - "codedeploy:CreateDeployment"
                      - "codedeploy:GetApplicationRevision"
                      - "codedeploy:GetDeployment"
                      - "codedeploy:GetDeploymentConfig"
                      - "codedeploy:RegisterApplicationRevision"
                    Resource: "*"
                  -
                    Effect: "Allow"
                    Action:
                      - "elasticbeanstalk:*"
                      - "ec2:*"
                      - "elasticloadbalancing:*"
                      - "autoscaling:*"
                      - "cloudwatch:*"
                      - "s3:*"
                      - "sns:*"
                      - "cloudformation:*"
                      - "rds:*"
                      - "sqs:*"
                      - "ecs:*"
                      - "iam:PassRole"
                    Resource: "*"
                  -
                    Effect: "Allow"
                    Action:
                      - "lambda:InvokeFunction"
                      - "lambda:ListFunctions"
                    Resource: "*"
                  -
                    Effect: "Allow"
                    Action:
                      - "opsworks:CreateDeployment"
                      - "opsworks:DescribeApps"
                      - "opsworks:DescribeCommands"
                      - "opsworks:DescribeDeployments"
                      - "opsworks:DescribeInstances"
                      - "opsworks:DescribeStacks"
                      - "opsworks:UpdateApp"
                      - "opsworks:UpdateStack"
                    Resource: "*"
                  -
                    Effect: "Allow"
                    Action:
                      - "cloudformation:CreateStack"
                      - "cloudformation:DeleteStack"
                      - "cloudformation:DescribeStacks"
                      - "cloudformation:UpdateStack"
                      - "cloudformation:CreateChangeSet"
                      - "cloudformation:DeleteChangeSet"
                      - "cloudformation:DescribeChangeSet"
                      - "cloudformation:ExecuteChangeSet"
                      - "cloudformation:SetStackPolicy"
                      - "cloudformation:ValidateTemplate"
                      - "iam:PassRole"
                    Resource: "*"
                  -
                    Effect: "Allow"
                    Action:
                      - "codebuild:BatchGetBuilds"
                      - "codebuild:StartBuild"
                    Resource: "*"
  CloudformationLambdaExecutionRole:
      Type: "AWS::IAM::Role"
      Properties:
          Path: "/"
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Sid: "AllowCloudformationToAssumeRole"
                Effect: "Allow"
                Action:
                  - "sts:AssumeRole"
                Principal:
                  Service:
                    - "cloudformation.amazonaws.com"
          Policies:
            -
              PolicyName: "InlinePolicy"
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  -
                    Effect: "Allow"
                    Action: "*"
                    Resource: "*"
  CodePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Join
          - '-'
          - - !Ref GitHubSourceRepositoryOwner
            - !Ref GitHubSourceRepositoryName
            - "pipeline"
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                -
                  Name: MyApp
              Configuration:
                Owner: !Ref GitHubSourceRepositoryOwner
                Repo: !Ref GitHubSourceRepositoryName
                Branch: !Ref GitHubSourceRepositoryBranch
                OAuthToken: !Ref GitHubPersonalAccessToken
              RunOrder: 1
        -
          Name: Build
          Actions:
            -
              Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                -
                  Name: MyApp
              OutputArtifacts:
                -
                  Name: MyAppBuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1
        -
          Name: Deploy
          Actions:
            -
              Name: ChangeSetBuild
              InputArtifacts:
                -
                  Name: MyAppBuild
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                ChangeSetName: !Join
                    - '-'
                    - - !Ref GitHubSourceRepositoryOwner
                      - !Ref GitHubSourceRepositoryName
                      - "changeset"
                RoleArn: !GetAtt CloudformationLambdaExecutionRole.Arn
                Capabilities: CAPABILITY_IAM
                StackName: !Join
                    - '-'
                    - - !Ref GitHubSourceRepositoryOwner
                      - !Ref GitHubSourceRepositoryName
                ParameterOverrides: !Join
                    - ''
                    - - '{"CloudWatchLogDestinationName": "'
                      - !Ref CloudWatchLogDestinationName
                      - '", "AlertMessageDynamoDBTableName": "'
                      - !Ref AlertMessageDynamoDBTableName
                      - '", "SlackWebHookUrl": "'
                      - !Ref SlackWebHookUrl
                      - '", "SlackChannel": "'
                      - !Ref SlackChannel
                      - '", "TeamsWebHookUrl": "'
                      - !Ref TeamsWebHookUrl
                      - '", "AlertTopicSubEndpointForCTO":"'
                      - !Ref AlertTopicSubEndpointForCTO
                      - '"}'
                TemplatePath: MyAppBuild::samTemplate.yaml
              RunOrder: 1
            -
              Name: ChangeSetExecute
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                StackName: !Join
                    - '-'
                    - - !Ref GitHubSourceRepositoryOwner
                      - !Ref GitHubSourceRepositoryName
                ChangeSetName: !Join
                    - '-'
                    - - !Ref GitHubSourceRepositoryOwner
                      - !Ref GitHubSourceRepositoryName
                      - "changeset"
              RunOrder: 2
            -
              !If
                - HasEncryptionLambda
                -
                  Name: EncryptLambdaSecretEnvVars
                  ActionTypeId:
                    Category: Invoke
                    Owner: AWS
                    Version: 1
                    Provider: Lambda
                  Configuration:
                    FunctionName: !Ref EncryptionLambdaName
                    UserParameters: !Join
                        - ''
                        - - "{\"stack_name\":\""
                          - !Ref GitHubSourceRepositoryOwner
                          - "-"
                          - !Ref GitHubSourceRepositoryName
                          - "\"}"
                  RunOrder: 3
                - !Ref "AWS::NoValue"
      ArtifactStore:
        Type: S3
        Location: !Ref InputArtifactS3Bucket

Outputs:
  ArtifactS3BucketName:
    Description: S3 Bucket Name to Store Artifacts
    Value: !Ref InputArtifactS3Bucket
  CodeBuildProjectName:
    Description: Created CodeBuild Project Name
    Value: !Ref CodeBuildProject
  CodePipelineProjectName:
    Description: Created CodePipeline Project Name
    Value: !Ref CodePipeline
