AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloudformation to Build SungardAS Alert System - For Different Regions and/or Accounts
Parameters:
  CloudWatchLogDestinationArn:
    Type: String
    Description: CloudWatch Log Destination Arn. This destination must be in the same region with current one.
  SampleLogGroupName:
    Type: String
    Default: "/SungardAS/Alerts/Sample"
    Description: Sample Cloudwatch Log Group Name

Resources:
  SampleLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join
        - "/"
        - - !Ref SampleLogGroupName
          - !Ref AWS::Region
  SubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    DependsOn: SampleLogGroup
    Properties:
      LogGroupName: !Join
        - "/"
        - - !Ref SampleLogGroupName
          - !Ref AWS::Region
      FilterPattern: ""
      DestinationArn: !Ref CloudWatchLogDestinationArn
  SampleLambdaFunctionIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "AllowLambdaServiceToAssumeRole"
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        -
          PolicyName: "InlinePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
              -
                Effect: "Allow"
                Action:
                  - "logs:*"
                  - "cloudwatchlogs:*"
                Resource: "*"
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join
        - "-"
        - - "SungardAS-Alerts-Sample-Alert"
          - !Ref AWS::Region
          - !Select [6, !Split [":", !Ref CloudWatchLogDestinationArn]]
      Handler: index_sample_alert.handler
      Runtime: nodejs4.3
      CodeUri: ./src
      Role: !GetAtt SampleLambdaFunctionIAMRole.Arn
      Timeout: 300
      Environment:
        Variables:
          SAMPLE_LOG_GROUP_NAME: !Join
            - "/"
            - - !Ref SampleLogGroupName
              - !Ref AWS::Region

Outputs:
  SampleAlertLambdaFunction:
    Description: "Sample Alert Lambda Function ARN"
    Value: !GetAtt SampleFunction.Arn
