AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloudformation to Build SungardAS Alert System
Parameters:
  CloudWatchLogDestinationName:
    Type: String
    Default: "alertDestination"
    Description: CloudWatch Log Destination Name To Send Alert To Kinesis Stream
  SlackWebHookUrl:
    Type: String
    NoEcho: true
    Description: Slack Webhook Url
  SlackChannel:
    Type: String
    Description: Slack Channel Name
  SampleLogGroupName:
    Type: String
    Default: "/SungardAS/Alerts/Sample"
    Description: Sample Cloudwatch Log Group Name

Resources:
  AlertTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  DynamoDBLambdaFunctionIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "AllowLambdaServiceToAssumeRole"
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        -
          PolicyName: "InlinePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
              -
                Effect: "Allow"
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:Query"
                Resource: "arn:aws:dynamodb:*"
              -
                Effect: "Allow"
                Action:
                  - "kinesis:DescribeStream"
                  - "kinesis:GetRecords"
                  - "kinesis:GetShardIterator"
                  - "kinesis:ListStreams"
                Resource: !GetAtt AlertStream.Arn
  DynamoDBLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SungardAS-Alerts-DynamoDB
      Handler: index_dynamodb.handler
      Runtime: nodejs4.3
      CodeUri: ./src
      Role: !GetAtt DynamoDBLambdaFunctionIAMRole.Arn
      Timeout: 60
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref AlertTable
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt AlertStream.Arn
            StartingPosition: TRIM_HORIZON
  AlertStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1
  SlackLambdaFunctionIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "AllowLambdaServiceToAssumeRole"
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        -
          PolicyName: "InlinePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
              -
                Effect: "Allow"
                Action:
                  - "kms:*"
                Resource: "*"
              -
                Effect: "Allow"
                Action:
                  - "kinesis:DescribeStream"
                  - "kinesis:GetRecords"
                  - "kinesis:GetShardIterator"
                  - "kinesis:ListStreams"
                Resource: !GetAtt AlertStream.Arn
  SlackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SungardAS-Alerts-Slack
      Handler: index_slack.handler
      Runtime: nodejs4.3
      CodeUri: ./src
      Role: !GetAtt SlackLambdaFunctionIAMRole.Arn
      Timeout: 300
      Environment:
        Variables:
          SLACK_HOOK_URL: !Ref SlackWebHookUrl
          SLACK_CHANNEL: !Ref SlackChannel
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt AlertStream.Arn
            StartingPosition: TRIM_HORIZON
  CWLtoKinesisRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "AllowCloudwatchlogsToAssumeRole"
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service: !Join
                - "."
                - - "logs"
                  - !Ref AWS::Region
                  - "amazonaws.com"
  CWLtoKinesisRolePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "CWLtoKinesisRolePolicy"
      Roles:
        - !Ref CWLtoKinesisRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "kinesis:PutRecord"
            Resource: !GetAtt AlertStream.Arn
          -
            Effect: "Allow"
            Action:
              - "iam:PassRole"
            Resource: !GetAtt CWLtoKinesisRole.Arn
  CloudWatchDestination:
    Type: AWS::Logs::Destination
    DependsOn: SlackFunction
    Properties:
      DestinationName: !Ref CloudWatchLogDestinationName
      RoleArn: !GetAtt CWLtoKinesisRole.Arn
      TargetArn: !GetAtt AlertStream.Arn
      DestinationPolicy: !Join
        - ""
        - - "{\"Version\" : \"2012-10-17\",\"Statement\" : [{\"Effect\" : \"Allow\", \"Principal\" : {\"AWS\" : [\""
          - !Ref "AWS::AccountId"
          - "\"]},\"Action\" : \"logs:PutSubscriptionFilter\", \"Resource\" : \"arn:aws:logs:"
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":destination:"
          - !Ref CloudWatchLogDestinationName
          - "\"}]}"
  SampleLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join
        - "/"
        - - !Ref SampleLogGroupName
          - !Ref AWS::Region
  SubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    DependsOn: SampleLogGroup
    Properties:
      LogGroupName: !Join
        - "/"
        - - !Ref SampleLogGroupName
          - !Ref AWS::Region
      FilterPattern: ""
      DestinationArn: !GetAtt CloudWatchDestination.Arn
  SampleLambdaFunctionIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "AllowLambdaServiceToAssumeRole"
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        -
          PolicyName: "InlinePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
              -
                Effect: "Allow"
                Action:
                  - "logs:*"
                  - "cloudwatchlogs:*"
                Resource: "*"
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join
        - "-"
        - - "SungardAS-Alerts-Sample-Alert"
          - !Ref AWS::Region
      Handler: index_sample_alert.handler
      Runtime: nodejs4.3
      CodeUri: ./src
      Role: !GetAtt SampleLambdaFunctionIAMRole.Arn
      Timeout: 300
      Environment:
        Variables:
          SAMPLE_LOG_GROUP_NAME: !Join
            - "/"
            - - !Ref SampleLogGroupName
              - !Ref AWS::Region
  AccountPermissionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "SungardAS-Alerts-Account-Permission"
      Handler: index_account_permission.handler
      Runtime: nodejs4.3
      CodeUri: ./src
      Role: !GetAtt SampleLambdaFunctionIAMRole.Arn
      Timeout: 300

Outputs:
  DynamoDBLambdaFunction:
    Description: "DynamoDB Lambda Function ARN"
    Value: !GetAtt DynamoDBLambdaFunction.Arn
  SlackAlertLambdaFunction:
    Description: "Slack Alert Lambda Function ARN"
    Value: !GetAtt SlackFunction.Arn
  SampleAlertLambdaFunction:
    Description: "Sample Alert Lambda Function ARN"
    Value: !GetAtt SampleFunction.Arn
  AccountPermissionLambdaFunction:
    Description: "Account Permission Lambda Function ARN"
    Value: !GetAtt AccountPermissionFunction.Arn
  KinesisStreamArn:
    Description: "Kinesis Alert Stream ARN"
    Value: !GetAtt AlertStream.Arn
  CloudWatchDestinationArn:
    Description: "CloudWatch Log Destination Arn"
    Value: !GetAtt CloudWatchDestination.Arn
